# Generated by Django 5.0.6 on 2024-04-29 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JOB', '0003_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(null=True, upload_to='')),
                ('applydate', models.DateField()),
                ('jobs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JOB.job')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JOB.studentuser')),
            ],
        ),
    ]
